{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
secrets:
  - name: {{ include "rabbitmq.fullname" . }}
{{- end }}
