affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
enableKubeStateMetrics: false
enableKubeWatch: false
fullnameOverride: ''
global:
  levoai:
    log_level: INFO
    mode: prod_k8s
    pi_detector_data_dir: /opt/levoai/datasets/
  levoai_config_override:
    authentication_inspection: false
    cookie_auth_keys: ''
    kube-state-metrics:
      url: http://kube-state-metrics:8080/
    min_urls_required_per_pattern: 10
    rabbitmq:
      host: levoai-rabbitmq
    service_naming:
      strategies: KUBERNETES_METADATA,DEFAULT
    tagger_batch_interval_minutes: 5
    tagger_ignore_seen_flows: true
    traces_log_level: DEBUG
    url_clusterer_id_len: 1
  serviceAnnotations: {}
  virtualService:
    enabled: false
    fullyQualifiedDomainName: ''
    gateway: ''
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: ''
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
kubewatch:
  fullnameOverride: levoai-kubewatch
levoai-collector:
  config:
    data:
      exporters:
        levoai_satellite:
          compression: none
          endpoint: http://levoai-satellite:9999
        logging:
          logLevel: info
      extensions:
        health_check:
          endpoint: 0.0.0.0:13133
        memory_ballast:
          size_mib: 512
      processors:
        batch:
          timeout: 10s
        levoai_merge:
          timeout: 10s
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              max_recv_msg_size_mib: 16
      service:
        extensions:
        - health_check
        - memory_ballast
        pipelines:
          traces:
            exporters:
            - logging
            - levoai_satellite
            processors:
            - levoai_merge
            - batch
            receivers:
            - otlp
    name: levoai-collector-conf
  containerPorts:
  - containerPort: 4317
    name: grpc-otel
  - containerPort: 13133
    name: http-health
  deploymentSelectorMatchLabels:
    app: levoai-collector
  env:
  - name: GOGC
    value: '80'
  fullnameOverride: levoai-levoai-collector
  image: levoai/collector
  imagePullPolicy: IfNotPresent
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  logLevel: INFO
  maxUnavailable: 0
  minReadySeconds: 5
  nodeSelector: {}
  podLabels:
    app: levoai-collector
  progressDeadlineSeconds: 120
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 400Mi
  service:
    ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    type: ClusterIP
  serviceSelectorLabels:
    app: levoai-collector
  volumeMounts:
  - mountPath: /conf
    name: levoai-collector-config-vol
  volumes:
  - configMap:
      items:
      - key: levoai-collector-config
        path: levoai-collector-config.yaml
      name: levoai-collector-conf
    name: levoai-collector-config-vol
nameOverride: ''
nginx:
  fullnameOverride: levoai-nginx
  pdb:
    create: true
    minAvailable: 1
  replicaCount: 2
  serverBlock: "server {\n    listen                8080 default_server deferred;\n\
    \    server_name           main;\n    client_max_body_size  20M;\n    keepalive_timeout\
    \ 5;\n    location / {\n        proxy_redirect off;\n        proxy_pass      \
    \                    http://levoai-satellite:9999;\n        proxy_set_header \
    \                   Host levoai-satellite;\n        proxy_http_version 1.1;\n\
    \        proxy_set_header X-Forwarded-Host   $server_name;\n        proxy_set_header\
    \ X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto\
    \ $scheme;\n        proxy_set_header X-Real-IP          $remote_addr;\n    }\n\
    }"
  service:
    port: 9999
    type: ClusterIP
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
rabbitmq:
  auth:
    erlangCookie: levoaierlangcookie
    password: levoailevoai
    username: levoai
  fullnameOverride: levoai-rabbitmq
replicaCount: 1
resources: {}
satellite:
  fullnameOverride: levoai-satellite
securityContext: {}
serviceAccount:
  annotations: {}
  create: true
  name: ''
tagger:
  fullnameOverride: levoai-tagger
tolerations: []
useNginx: false
