apiVersion: v2
appVersion: 0.2.639
dependencies:
- condition: global.useRabbitmq
  name: rabbitmq
  repository: file://dependencies/rabbitmq
  version: 12.4.2
- name: satellite
  repository: file://dependencies/satellite
  version: 0.2.639
- name: tagger
  repository: file://dependencies/tagger
  version: 0.2.639
- condition: global.levoai_config_override.api_rule_evaluation.enabled
  name: levoai-ion
  repository: file://dependencies/ion
  version: 0.2.639
- name: levoai-collector
  repository: '@levoai-private'
  version: 0.21.1
- condition: haproxy.enabled
  name: haproxy
  repository: file://dependencies/haproxy
  version: 1.0.6
description: The Levoai Satellite Service, which receives observations from the Sensor/Envoy
  filters et al.
name: levoai-satellite
type: application
version: 0.2.639
