apiVersion: v2
appVersion: 1.2.724
dependencies:
- condition: global.useRabbitmq
  name: rabbitmq
  repository: file://dependencies/rabbitmq
  version: 12.4.2
- name: satellite
  repository: file://dependencies/satellite
  version: 1.2.724
- name: tagger
  repository: file://dependencies/tagger
  version: 1.2.724
- condition: global.levoai_config_override.api_rule_evaluation.enabled
  name: levoai-ion
  repository: file://dependencies/ion
  version: 1.2.724
- name: levoai-collector
  repository: '@levoai-private'
  version: 0.24.2
- condition: haproxy.enabled
  name: haproxy
  repository: file://dependencies/haproxy
  version: 1.0.6
- condition: testrunner.enabled
  name: testrunner
  repository: file://dependencies/testrunner
  version: '>=0.1.0'
description: The Levoai Satellite Service, which receives observations from the Sensor/Envoy
  filters et al.
name: levoai-satellite
type: application
version: 1.2.724
