apiVersion: v2
appVersion: 0.2.294
dependencies:
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 10.1.14
- name: satellite
  repository: file://dependencies/satellite
  version: 0.2.294
- name: tagger
  repository: file://dependencies/tagger
  version: 0.2.294
- condition: global.levoai_config_override.api_rule_evaluation.enabled
  name: levoai-ion
  repository: file://dependencies/ion
  version: 0.4.0
- condition: useNginx
  name: nginx
  repository: file://dependencies/nginx
  version: 8.5.5
- condition: enableKubeWatch
  name: kubewatch
  repository: file://dependencies/kubewatch
  version: 1.0.1
- condition: enableKubeStateMetrics
  name: kube-state-metrics
  repository: file://dependencies/kube-state-metrics
  version: 2.0.0
- name: levoai-collector
  repository: '@levoai-private'
  version: 0.13.0
description: The Levoai Satellite Service, which receives observations from the Sensor/Envoy
  filters et al.
name: levoai-satellite
type: application
version: 0.2.294
