apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecar-injector.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
data:
  injector-config.yaml: |
    sidecarImage:
      registry: {{ default "" .Values.sidecar.image.registry | quote }}
      repository: {{ .Values.sidecar.image.repository | quote }}
      tag: {{ default .Chart.AppVersion .Values.sidecar.image.tag | quote }}
      pullPolicy: "IfNotPresent"
    sidecarResources:
      cpuRequest: {{ .Values.sidecar.resources.requests.cpu | quote }}
      cpuLimit: {{ .Values.sidecar.resources.limits.cpu | quote }}
      memoryRequest: {{ .Values.sidecar.resources.requests.memory | quote }}
      memoryLimit: {{ .Values.sidecar.resources.limits.memory | quote }}
    sidecarPorts:
      transparent: {{ .Values.sidecar.ports.transparent }}
      proxy: {{ .Values.sidecar.ports.proxy }}
      admin: {{ .Values.sidecar.ports.admin }}
    sidecarUid: {{ .Values.sidecar.uid }}
    tls:
      caSecretName: {{ .Values.tls.caSecretName | quote }}
      generateCa: {{ .Values.tls.generateCA }}
    controlPlane:
      endpoint: {{ .Values.controlPlane.endpoint | quote }}
      authSecretName: {{ .Values.controlPlane.authSecretName | quote }}
    meshCoexistence:
      autoDetect: {{ .Values.meshCoexistence.autoDetect }}
      istio:
        excludeFromIstioCapture: {{ .Values.meshCoexistence.istio.excludeFromIstioCapture }}
      linkerd:
        excludeFromLinkerdCapture: {{ .Values.meshCoexistence.linkerd.excludeFromLinkerdCapture }}
    defaultInterceptMode: {{ .Values.defaultInterceptMode | quote }}
    defaultInterceptPorts:
      {{- range (splitList "," .Values.defaultInterceptPorts) }}
      - {{ . | trim }}
      {{- end }}
    {{- if .Values.defaultExcludePorts }}
    defaultExcludePorts:
      {{- range (splitList "," .Values.defaultExcludePorts) }}
      - {{ . | trim }}
      {{- end }}
    {{- end }}
    {{- if .Values.defaultExcludeCIDRs }}
    defaultExcludeCidrs:
      {{- range (splitList "," .Values.defaultExcludeCIDRs) }}
      - {{ . | trim | quote }}
      {{- end }}
    {{- end }}
    excludedNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
      {{- range .Values.webhook.excludedNamespaces }}
      - {{ . | quote }}
      {{- end }}
    webhookPort: {{ .Values.webhook.port }}
    healthPort: 8080
