apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  name: {{ .Chart.Name }}
  labels:
    app: levoai-collector
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
  {{ end }}
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
