logLevel: INFO

minReadySeconds: 5
progressDeadlineSeconds: 120
replicaCount: 1
maxUnavailable: 0

image: levoai/collector
imagePullPolicy: IfNotPresent

env:
  - name: GOGC
    value: "80"

containerPorts:
  - name: grpc-otel
    containerPort: 4317
  - name: http-health
    containerPort: 13133

service:
  type: ClusterIP
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
    protocol: TCP

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  port: http-health

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  port: http-health

resources:
   limits:
     cpu: 1
     memory: 2Gi
   requests:
     cpu: 200m
     memory: 400Mi

podLabels:
  app: levoai-collector

deploymentSelectorMatchLabels:
  app: levoai-collector

serviceSelectorLabels:
  app: levoai-collector

volumeMounts:
  - name: levoai-collector-config-vol
    mountPath: /conf

volumes:
  - configMap:
      name: levoai-collector-conf
      items:
        - key: levoai-collector-config
          path: levoai-collector-config.yaml
    name: levoai-collector-config-vol

nodeSelector: {}

config:
  name: levoai-collector-conf
  data:
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
      memory_ballast:
        size_mib: 512

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 16

    processors:
      levoai_merge:
        timeout: 10s
      batch:
        timeout: 10s

    exporters:
      logging:
        logLevel: info
      levoai_satellite:
        endpoint: http://levoai-satellite:9999
        # Python Flask server in Levo's Satellite doesn't support gzip so don't enable any compression here.
        compression: none

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [levoai_merge, batch]
          exporters: [logging, levoai_satellite]

      extensions: [health_check, memory_ballast]
