replicaCount: 1

global:
  imageRegistry: ""
  imagePullSecrets: []

image:
  registry: docker.io
  repository: levoai/satellite
  pullPolicy: IfNotPresent
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
