replicaCount: 1

global:
  imageRegistry: ""
  imagePullSecrets: []
  multiTenancyEnabled: false

image:
  registry: docker.io
  repository: levoai/satellite
  pullPolicy: IfNotPresent
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

otel:
  enabled: false
  env:
    OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector.signoz:4317
    OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev
    OTEL_SERVICE_NAME: Ion
    OTEL_METRICS_EXPORTER: otlp
    OTEL_TRACES_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc