apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "kubewatch.fullname" . }}-env"
  labels:
    app: {{ template "kubewatch.name" . }}
    chart: {{ template "kubewatch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  LEVOAI_MODE: {{ .Values.global.levoai.mode }}
  LEVOAI_LOG_LEVEL: {{ .Values.global.levoai.log_level }}
  LEVOAI_CONF_OVERRIDES: '{{ mustToJson .Values.global.levoai_config_override }}'
