{{- $configMapEnabled := eq (include "aigateway.config.configMap.enabled" .) "true" }}
{{- $configMapCreate := eq (include "aigateway.config.configMap.create" .) "true" }}
{{- if and $configMapEnabled $configMapCreate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aigateway.config.configMap.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.configMap.data | indent 4 }}
{{- end }}
