# Default values for kube-state-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount:
  create: true

## Role Based Access
## ref: https://kubernetes.io/docs/admin/authorization/rbac/
rbac:
  ## Specifies whether RBAC rules should be created
  ## binding kube-state-metrics ServiceAccount to a role
  ## that allows kube-state-metrics pods querying the K8s API
  create: true

# TODO: node affinity with kubewatch would be nice:
# affinity: {}
service:
  annotations: {}
