apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: levoai-pcap-sensor
spec:
  template:
    metadata:
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ .Values.sensor.config | toString | sha256sum }}
      labels:
        name: levoai-pcap-sensor
    spec:
      {{- if .Values.sensor.tolerations }}
      tolerations: {{- toYaml .Values.sensor.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.sensor.nodeSelector }}
      nodeSelector: {{- toYaml .Values.sensor.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: pcap-sensor
          image: {{ .Values.sensor.imageRepo }}:{{ .Values.sensor.imageTag }}
          imagePullPolicy: Always
          {{- if .Values.sensor.containerResources }}
          resources: {{- toYaml .Values.sensor.containerResources | nindent 12 }}
          {{- end }}
          # Overrides docker image's entrypoint.
          command:
            - /levoai/pcap-sensor/bin/init
          args:
            - "apidump"
            {{- if .Values.sensor.config.satelliteUrl }}
            - "--satellite-url"
            - {{ .Values.sensor.config.satelliteUrl }}
            {{- end}}
            {{- if .Values.sensor.config.levoEnv }}
            - "--levo-env"
            - {{ .Values.sensor.config.levoEnv }}
            {{- end}}
            {{- if .Values.sensor.config.traceExportInterval }}
            - "--trace-export-interval"
            - "{{ .Values.sensor.config.traceExportInterval }}"
            {{- end}}
            {{- if .Values.sensor.config.rateLimit }}
            - "--rate-limit"
            - "{{ .Values.sensor.config.rateLimit }}"
            {{- end}}
            {{- if .Values.sensor.config.filter }}
            - "--filter"
            - {{ .Values.sensor.config.filter }}
            {{- end}}
            {{- if .Values.sensor.config.hostAllow }}
            - "--host-allow"
            - {{ .Values.sensor.config.hostAllow }}
            {{- end}}
            {{- if .Values.sensor.config.pathAllow }}
            - "--path-allow"
            - {{ .Values.sensor.config.pathAllow }}
            {{- end}}
            {{- if .Values.sensor.config.hostExclusions }}
            - "--host-exclusions"
            - {{ .Values.sensor.config.hostExclusions }}
            {{- end}}
            {{- if .Values.sensor.config.pathExclusions }}
            - "--path-exclusions"
            - {{ .Values.sensor.config.pathExclusions }}
            {{- end}}
            {{- if .Values.sensor.config.levoaiOrgId }}
            - "--levoai-org-id"
            - {{ .Values.sensor.config.levoaiOrgId }}
            {{- end}}
            {{- if .Values.sensor.config.levoaiWorkspaceId }}
            - "--levoai-workspace-id"
            - {{ .Values.sensor.config.levoaiWorkspaceId }}
            {{- end}}
            {{- if .Values.sensor.config.maxHttpLength }}
            - "--max-http-length"
            - "{{ .Values.sensor.config.maxHttpLength }}"
            {{- end}}
            {{- if .Values.sensor.config.streamTimeoutSeconds }}
            - "--stream-timeout-seconds"
            - "{{ .Values.sensor.config.streamTimeoutSeconds }}"
            {{- end}}
          securityContext:
            capabilities:
              add: ["NET_RAW"]
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- if .Values.sensor.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.sensor.imagePullSecretName }}
      {{- end }}
  selector:
    matchLabels:
      name: levoai-pcap-sensor
