apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: levoai-sensor
spec:
  template:
    metadata:
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ .Values.sensor.config | toString | sha256sum }}
        {{- if .Values.podAnnotations }}
          {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        name: levoai-sensor
    spec:
      {{- if .Values.sensor.tolerations }}
      tolerations: {{- toYaml .Values.sensor.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.sensor.affinity }}
      affinity: {{- toYaml .Values.sensor.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.sensor.nodeSelector }}
      nodeSelector: {{- toYaml .Values.sensor.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: levoai-sensor
          image: {{ .Values.sensor.imageRepo }}:{{ .Values.sensor.imageTag }}
          imagePullPolicy: Always
          {{- if .Values.sensor.containerResources }}
          resources: {{- toYaml .Values.sensor.containerResources | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.sensor.env }}
            - name: {{ $value.name }}
              value: "{{ $value.value }}"
            {{- end }}
            - name: OUTSIDE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: levoai-sensor
                  resource: limits.memory
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: levoai-sensor
                  resource: limits.cpu
          # Overrides docker image's entrypoint.
          command:
            - /sbin/init_lite
          args:
            - "--host-proc-path"
            - "/host/proc"
            - "--levo-env"
            - {{ .Values.sensor.levoEnv }}
            - "--satellite-url"
            - {{ .Values.sensor.satelliteUrl }}
            - "--organization-id"
            - {{ default "" .Values.sensor.orgId }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: etc/levo/sensor
              readOnly: true
            - mountPath: /host/proc
              name: host-proc
              readOnly: true
            - mountPath: /sys/kernel/tracing
              name: sys-kernel-debug
              readOnly: true
      {{- if .Values.sensor.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.sensor.imagePullSecretName }}
      {{- end }}
      serviceAccountName: {{ .Values.sensor.serviceAccount.name }}
      volumes:
        - name: config
          configMap:
            name: sensor-config
            items:
              - key: config-file-content
                path: config.yaml
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug/tracing
        - name: host-proc
          hostPath:
            path: /proc
  selector:
    matchLabels:
      name: levoai-sensor
