apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: levoai-sensor
spec:
  template:
    metadata:
      labels:
        name: levoai-sensor
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: levoai-sensor
          {{ if.Values.sensor.cpus }}
          resources:
            requests:
              cpu: {{ .Values.sensor.cpus }}
          {{ end -}}
          image: {{ .Values.sensor.imageRepo }}:{{ .Values.sensor.imageTag }}
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.sensor.otel.grpcEndpoint }}
          # Overrides docker image's entrypoint.
          command: {{ mustToJson .Values.sensor.binary }}
          securityContext:
            # NOTE: capabilities.add: ["SYS_ADMIN", "SYS_RESOURCE"] wasn't enough to read real addresses from
            #   /proc/kallsyms, or access /proc/PID/maps or /proc/PID/root in all cases.
            privileged: true
          volumeMounts:
            - name: config
              mountPath: etc/levo/sensor
              readOnly: true
            - mountPath: /sys/kernel/debug
              name: sys-kernel-debug
              readOnly: true
            - mountPath: /host/proc
              name: host-proc
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.sensor.imagePullSecretName }}
      volumes:
        - name: config
          configMap:
            name: sensor-config
            items:
              - key: config-file-content
                path: config.yaml
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: host-proc
          hostPath:
            path: /proc
  selector:
    matchLabels:
      name: levoai-sensor
