apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: levoai-sensor
spec:
  template:
    metadata:
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ .Values.sensor.config | toString | sha256sum }}
      labels:
        name: levoai-sensor
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: levoai-sensor
          {{ if .Values.sensor.cpus }}
          resources:
            requests:
              cpu: {{ .Values.sensor.cpus }}
          {{ end }}
          image: {{ .Values.sensor.imageRepo }}:{{ .Values.sensor.imageTag }}
          imagePullPolicy: Always
          env:
            - name: OUTSIDE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          # Overrides docker image's entrypoint.
          command:
            - /sbin/init_lite
          args:
            - "--host-proc-path"
            - "/host/proc"
          securityContext:
            # NOTE: capabilities.add: ["SYS_ADMIN", "SYS_RESOURCE"] wasn't enough to read real addresses from
            #   /proc/kallsyms, or access /proc/PID/maps or /proc/PID/root in all cases.
            privileged: true
          volumeMounts:
            - name: config
              mountPath: etc/levo/sensor
              readOnly: true
            - mountPath: /host/proc
              name: host-proc
              readOnly: true
            - mountPath: /sys/kernel/debug
              name: sys-kernel-debug
              readOnly: false
      {{ if .Values.sensor.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.sensor.imagePullSecretName }}
      {{ end }}
      serviceAccountName: {{ .Values.sensor.serviceAccount.name }}
      volumes:
        - name: config
          configMap:
            name: sensor-config
            items:
              - key: config-file-content
                path: config.yaml
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: host-proc
          hostPath:
            path: /proc
  selector:
    matchLabels:
      name: levoai-sensor
