{{- if .Values.sensor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sensor.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.sensor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.sensor.serviceAccount.name }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.sensor.serviceAccount.name }}-role-binding
roleRef:
  kind: ClusterRole
  name: {{ .Values.sensor.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sensor.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
# Starting with Kubernetes 1.24, ServiceAccount token secrets are no longer automatically generated.
# See "Urgent Upgrade Notes" in the 1.24 changelog:
# https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
apiVersion: v1
kind: Secret
metadata:
  name: levoai-ebpf-sensor-service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.sensor.serviceAccount.name }}"
type: kubernetes.io/service-account-token
