---
sensor:
  imageRepo: docker.io/levoai/pcap-sensor
  imageTag: 0.2.5
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector: {}
  containerResources:
    requests:
      cpu: 0.5
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  config:
    satelliteUrl: "http://levoai-satellite:9999"
    levoEnv: "staging"
    traceExportInterval: "10.0"
    rateLimit: "1000.0"
    filter: ""
    hostAllow: ""
    pathAllow: ""
    hostExclusions: ""
    pathExclusions: ""
    levoaiOrgId: ""
    levoaiWorkspaceId: ""
    maxHttpLength: ""
    streamTimeoutSeconds: ""
