apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagOverride | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LEVOAI_BASE_URL
              value: {{ .Values.levoBaseUrl }}
            - name: NEXT_PUBLIC_LEVOAI_AUTH_KEY
              value: "{{ .Values.levoAuthKey }}"
            - name: NEXT_PUBLIC_LEVOAI_ORG_ID
              value: "{{ .Values.levoOrgId }}"
            - name: ALLOWED_ORIGINS
              value: "{{ .Values.allowedOrigins }}"
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            {{- if .Values.hostedOnLevo }}
            - name: NEXT_PUBLIC_API_BASE_URL
              value: {{ .Values.levoBaseUrl }}
            {{- end }}
            - name: NEXT_PUBLIC_BASE_PATH
              value: {{ .Values.basePath | quote }}

          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 90
            periodSeconds: 30
            httpGet:
              path: /
              port: http
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 30

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
