replicaCount: 1

image:
  repository: levoai/api-portal
  pullPolicy: IfNotPresent
  tagOverride: ""

levoAuthKey: ""
levoBaseUrl: "https://api.levo.ai"
levoOrgId: ""
basePath: "/apiportal"
allowedOrigins: "*"
logLevel: "INFO"
hostedOnLevo: false

istio:
  enabled: false
  host: "*"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  corsWebOrigin:
    app: "https://app.levo.ai"
  enableLocalhostCors: false

gateway:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: api-local.local
      paths:
        - path: /apiportal
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
