apiVersion: apps/v1
kind: Deployment
metadata:
  name: testrunner
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: LOCAL_USER_ID
            value: "{{ .Values.localUserId }}"
          - name: LOCAL_GROUP_ID
            value: "{{ .Values.localGroupId }}"
          - name: TERM
            value: "xterm-256color"
          - name: LEVO_BASE_URL
            value: "{{ .Values.levoBaseUrl }}"
          tty: true
          args:
              [
               "start",
               "--key",
               "{{ .Values.refreshToken }}",
               "--organization",
               "{{ .Values.orgId }}"
              ]
          workingDir: /home/levo/work
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # volumes:
      #   - name: configstore
      #     hostPath:
      #       path: {{ .Values.configstorePath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
