apiVersion: v1
kind: ConfigMap
metadata:
  name: levoai-filebeat-config
  labels:
    app: levoai-filebeat
    app.kubernetes.io/name: levoai-filebeat-config
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  filebeat.yml: |
{{ .Files.Get "config/filebeat.yml" | indent 4 }}
