apiVersion: v1
kind: ConfigMap
metadata:
  name: levoai-logstash-config
  labels:
    app: levoai-logstash
    app.kubernetes.io/name: levoai-logstash-config
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  logstash.conf: |
{{ .Files.Get "config/logstash.conf" | indent 4 }}
  logstash.yml: |
{{ .Files.Get "config/logstash.yml" | indent 4 }}
