apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: levoai-collector
    release: {{ .Release.Name }}
spec:
  minReadySeconds: {{ .Values.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.podLabels | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - "/usr/local/bin/levoai/collector"
            - "--config=/conf/levoai-collector-config.yaml"
          ports:
          {{ range $port := .Values.containerPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.containerPort }}
          {{ end }}
        {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12}}
        {{- end }}
        {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12}}
        {{- end }}
          livenessProbe:
            initialDelaySeconds: {{ int .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.livenessProbe.periodSeconds }}
            tcpSocket:
              port: 4318
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
