{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "protection.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "protection.name" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "protection.name" . }}
{{- end }}
