{{- if and .Values.tls.enabled .Values.tls.existingSecretName }}
# Using an existing secret; nothing to create here.
{{- else if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protection.name" . }}-tls
type: kubernetes.io/tls
data:
  # Provide base64-encoded cert/key via values override or use cert-manager to create it externally.
  tls.crt: ""
  tls.key: ""
{{- end }}
