apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satellite.fullname" . }}
  labels:
    {{- include "satellite.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "satellite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with deepCopy .Values.podAnnotations | mustMerge (dict "rollme" (randAlphaNum 10)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "satellite.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "satellite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-rabbitmq
          image: levoai/rmq_healthcheck:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-w"
            - "1"
            - "-b"
            - "0.0.0.0:{{ .Values.service.port }}"
            - "--worker-class"
            - "gevent"
            - "--worker-connections"
            - "30"
            - "levoai_e7s.satellite.satellite:create_server()"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: "{{ template "satellite.fullname" . }}-env"
          livenessProbe:
            httpGet:
              path: /_status
              port: http
          readinessProbe:
            httpGet:
              path: /_status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
