apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satellite.fullname" . }}
  labels:
    {{- include "satellite.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "satellite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- /*
    # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
    */}}
    {{- with deepCopy .Values.global.podAnnotations | mustMerge (dict "checksum/config" (include (print $.Template.BasePath "/configmap-env.yaml") . | toString | sha256sum)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "satellite.selectorLabels" . | nindent 8 }}
    spec:
      {{- with (default .Values.image.pullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "satellite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.global.useRabbitmq }}
      initContainers:
        - name: wait-for-rabbitmq
          image: {{ default .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.global.busyboxImage }}
          command: [ 'sh', '-c', 'until wget -qO- http://levoai:levoailevoai@levoai-rabbitmq:15672/api/health/checks/local-alarms &> /dev/null; do echo waiting for rabbitmq; sleep 2; done;' ]
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ default .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.otel.enabled }}
          command:
            - "opentelemetry-instrument"
            - "gunicorn"
            - "--capture-output"
            - "--enable-stdio-inheritance"
            - "-c"
            - "/opt/levoai/common-public/src/python/levoai_common_public/gun.conf.py"
          {{end}}
          args:
            - "-w"
            - "{{ .Values.workers  }}"
            - "-b"
            - "0.0.0.0:{{ .Values.service.port }}"
            - "--worker-tmp-dir"
            - "/dev/shm"
            - "--worker-class"
            - "uvicorn.workers.UvicornWorker"
            - "--worker-connections"
            - "{{ .Values.workerConnections }}"
            - "--timeout"
            - "{{ .Values.workerTimeout }}"
            - "levoai_e7s.satellite.satellite:create_server()"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: "{{ template "satellite.fullname" . }}-env"
          env:
            {{- if .Values.env }}
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            {{- if .Values.otel.enabled }}
              {{- range $key, $value := .Values.otel.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
            - name: OTEL_ENABLED
              value: {{ .Values.otel.enabled | quote }}
          livenessProbe:
            httpGet:
              path: /_status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /_status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
