logLevel: INFO

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

minReadySeconds: 5
progressDeadlineSeconds: 120
replicaCount: 1
maxUnavailable: 0

image: levoai/collector
imagePullPolicy: IfNotPresent

env:
  - name: GOGC
    value: "80"

containerPorts:
  - name: grpc-otel
    containerPort: 4317
  - name: http-otel
    containerPort: 4318
  - name: http-health
    containerPort: 13133

service:
  type: ClusterIP
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: http-otlp
    port: 4318
    targetPort: 4318
    protocol: TCP

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  port: http-health

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  port: http-health

resources:
   limits:
     cpu: 1
     memory: 2Gi
   requests:
     cpu: 200m
     memory: 400Mi
     ephemeral-storage: 64Ki

podLabels:
  app: levoai-collector

deploymentSelectorMatchLabels:
  app: levoai-collector

serviceSelectorLabels:
  app: levoai-collector

volumeMounts:
  - name: levoai-collector-config-vol
    mountPath: /conf

volumes:
  - configMap:
      name: levoai-collector-conf
      items:
        - key: levoai-collector-config
          path: levoai-collector-config.yaml
    name: levoai-collector-config-vol

nodeSelector: {}

tolerations: []

affinity: {}

config:
  name: levoai-collector-conf
  data:
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
      memory_ballast:
        size_in_percentage: 30

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 16
          http:
            endpoint: 0.0.0.0:4318
    processors:
      levoai_merge:
        timeout: 60s
      batch:
        # send_batch_size is the maximum number of spans to be sent in a single batch.
        # Keep it low so that we don't send too large of a batch to Levo's Satellite.
        send_batch_size: 20
        send_batch_max_size: 50
        timeout: 5s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 60
        spike_limit_percentage: 20

    exporters:
      logging:
        verbosity: normal
      levoai_satellite:
        endpoint: http://levoai-satellite:9999
        # Python Flask server in Levo's Satellite doesn't support gzip so don't enable any compression here.
        compression: none
      otlphttp:
        endpoint: http://levoai-satellite:9999
        compression: none

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, levoai_merge, batch]
          exporters: [logging, levoai_satellite]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlphttp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
      extensions: [health_check, memory_ballast]
