{{- if (default (default .Values.global.virtualService dict).enabled false) -}}
{{- $fullName := include "satellite.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: satellite
spec:
  hosts:
  - {{ .Values.global.virtualService.fullyQualifiedDomainName }}
  gateways:
  - {{ .Values.global.virtualService.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ $fullName }}{{ if .Release.Namespace }}{{ (print "." .Release.Namespace) }}{{ end }}.svc.cluster.local
        port:
          number: {{ $svcPort }}
{{- end -}}
