name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'levoai/**'
      - '!levoai/levoai-satellite/**'
      - '!levoai/levoai-ebpf-sensor/**'
  workflow_dispatch:

# Make sure there is only one instance of this workflow running at any time so that we don't override charts
concurrency: charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Exclude charts
        run: |
          rm -rf levoai/levoai-satellite
          rm -rf levoai/levoai-ebpf-sensor

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: levoai
          charts_repo_url: https://charts.levo.ai
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
