name: Release Private Satellite Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: Private Chart Version
        required: false
        type: string

jobs:
  release:
    uses: ./.github/workflows/release-private-chart.yaml
    with:
      name: levoai-satellite
      version: ${{ inputs.version }}
    secrets: inherit
