name: Release Sensor Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: Private Chart Version
        required: false
        type: string

jobs:
  release:
    uses: ./.github/workflows/release-private-chart.yaml
    with:
      name: levoai-ebpf-sensor
      version: ${{ inputs.version }}
    secrets: inherit
