name: Release Private Chart

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: false
        type: string

concurrency: charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "levobot"
          git config user.email "github-bot@levo.ai"

      - uses: google-github-actions/setup-gcloud@v0.6.2
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Download Private Chart
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git || echo "Helm plugin already exists."
          helm repo add levoai-private ${{ secrets.HELM_GCS_REPOSITORY }} || echo "Helm repo already exists"
          helm repo update
          mkdir -p .cr-release-packages
          cd .cr-release-packages
          helm pull levoai-private/${{ inputs.name }} --version "${{ inputs.version }}"

      - name: Release Chart
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_repo_url: https://charts.levo.ai
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
